# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 1000

palette = "base16-onedark"

scan_timeout = 30

# Format with OS symbol first
format = "$os$all"

[palettes.base16-onedark]
base00 = "#282c34"
base01 = "#353b45"
base02 = "#3e4451"
base03 = "#545862"
base04 = "#565c64"
base05 = "#abb2bf"
base06 = "#b6bdca"
base07 = "#c8ccd4"
base08 = "#e06c75"
base09 = "#d19a66"
base0A = "#e5c07b"
base0B = "#98c379"
base0C = "#56b6c2"
base0D = "#61afef"
base0E = "#c678dd"
base0F = "#be5046"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
ignore_submodules = true

[aws]
symbol = "aws "
disabled = true

[azure]
symbol = "az "
disabled = true

[bun]
symbol = "bun "

[c]
symbol = "C "
disabled = true

[cobol]
symbol = "cobol "
disabled = true

[conda]
symbol = "conda "
disabled = true

[crystal]
symbol = "cr "
disabled = true

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "
disabled = true

[dart]
symbol = "dart "
disabled = true

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "
disabled = true

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "
disabled = true

[elm]
symbol = "elm "
disabled = true

[fennel]
symbol = "fnl "
disabled = true

[fossil_branch]
symbol = "fossil "
disabled = true

[gcloud]
symbol = "gcp "
disabled = true

[git_branch]
symbol = "git "

[gleam]
symbol = "gleam "
disabled = true

[golang]
symbol = "go "

[gradle]
symbol = "gradle "
disabled = true

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "
disabled = true

[hostname]
ssh_symbol = "ssh "

[java]
symbol = "java "
disabled = true

[julia]
symbol = "jl "
disabled = true

[kotlin]
symbol = "kt "
disabled = true

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "

[nats]
symbol = "nats "
disabled = true

[nim]
symbol = "nim "
disabled = true

[nix_shell]
symbol = "nix "
disabled = true

[ocaml]
symbol = "ml "
disabled = true

[opa]
symbol = "opa "
disabled = true

[os]
disabled = false

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "♜ "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "♜ "
Mabox = "mbox "
Macos = "▲ "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unk "
Void = "void "
Windows = "win "

[package]
symbol = "pkg "
disabled = true

[perl]
symbol = "pl "
disabled = true

[php]
symbol = "php "
disabled = true

[pijul_channel]
symbol = "pijul "
disabled = true

[pulumi]
symbol = "pulumi "
disabled = true

[purescript]
symbol = "purs "
disabled = true

[python]
symbol = "py "

[quarto]
symbol = "quarto "
disabled = true

[raku]
symbol = "raku "
disabled = true

[ruby]
symbol = "rb "
disabled = true

[rust]
symbol = "rs "

[scala]
symbol = "scala "
disabled = true

[spack]
symbol = "spack "
disabled = true

[solidity]
symbol = "solidity "
disabled = true

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "
disabled = true

[typst]
symbol = "typst "
disabled = true

[terraform]
symbol = "terraform "
disabled = true


[zig]
symbol = "zig "
disabled = true
